Cerad\Bundle\GameBundle\Entity\League:
    type:  entity
    table: league
    changeTrackingPolicy: NOTIFY
    repositoryClass:      Cerad\Bundle\GameBundle\EntityRepository\LeagueRepository
    
    id:
        id:
            type: string
            generator: { strategy: NONE }
            
    fields:
        desc1:
            column: desc1
            type: string
            nullable: true
        desc2:
            type: string
            nullable: true
        city:
            type: string
            nullable: true
        state:
            type: string
            nullable: true
        status:
            type: string
            nullable: false
        datax:
            type: array
            nullable: true

    manyToOne:
        parent:
            targetEntity: League
            nullable: true
            joinColumn:
                name:          parent_id
                referencedColumnName: id
