services:
  
# ==============================================================
#   Entity Managers
# Have some dups because transitioning to different naming scheme
    cerad.game.entity_manager:
        alias: doctrine.orm.games_entity_manager
        
    cerad_game.entity_manager:
        alias: doctrine.orm.games_entity_manager
        

# ==============================================================
#   My Repositoriess
    cerad.project.repository:
        class:  Cerad\Bundle\GameBundle\EntityRepository\ProjectRepository
        factory_service: 'cerad_game.entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Project'
            
    cerad.level.repository:
        class:  Cerad\Bundle\GameBundle\EntityRepository\LevelRepository
        factory_service: 'cerad_game.entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Level'
            
    cerad.field.repository:
        class:  Cerad\Bundle\GameBundle\EntityRepository\FieldRepository
        factory_service: 'cerad_game.entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Field'
            
    cerad.game.repository:
        class:  Cerad\Bundle\GameBundle\EntityRepository\GameRepository
        factory_service: 'cerad_game.entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Game'
            
    cerad_game.league.repository:
        class:  Cerad\Bundle\GameBundle\EntityRepository\LeagueRepository
        factory_service: 'cerad_game.entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\League'

# ========================================================
# Generally like to think in terms of managers
# Eventually rename all the above repo services
# But use aliases for the transition
    cerad_game.league.manager:
        alias: cerad_game.league.repository

# ========================================================
# Game Forms
    cerad_game.report.form_type:
        class: Cerad\Bundle\GameBundle\Form\Type\Game\Report\GameFormType
        tags:
            - { name: form.type, alias: cerad_game_report_game }

