services:
  
# ==============================================================
#   Entity Managers
    cerad.game.entity_manager:
        alias: doctrine.orm.games_entity_manager
        
# ==============================================================
#   My Managers
    cerad.game.manager:
        class:  Cerad\Bundle\GameBundle\Manager\GameManager
        arguments:  
            - '@cerad.game.entity_manager'
            - 'games'
            - 'Cerad\Bundle\GameBundle\Entity\Game'
            
    cerad.project.manager:
        class:  Cerad\Bundle\GameBundle\Manager\ProjectManager
        arguments:  
            - '@cerad.game.entity_manager'
            - 'games'
            - 'Cerad\Bundle\GameBundle\Entity\Project'
            
    cerad.level.manager:
        class:  Cerad\Bundle\GameBundle\Manager\LevelManager
        arguments:  
            - '@cerad.game.entity_manager'
            - 'games'
            - 'Cerad\Bundle\GameBundle\Entity\Level'
            
    cerad.field.manager:
        class:  Cerad\Bundle\GameBundle\Manager\FieldManager
        arguments:  
            - '@cerad.game.entity_manager'
            - 'games'
            - 'Cerad\Bundle\GameBundle\Entity\Field'
