
services:
    cerad_account.registration.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cerad_account_registration }
            
    cerad_account.user_provider:
        class: Cerad\Bundle\AccountBundle\Security\AccountUserProvider
        arguments: ['@fos_user.user_manager']
        
    cerad_account.user_manager:
        class: Cerad\Bundle\AccountBundle\Security\AccountUserManager
        parent:   fos_user.user_manager.default
        arguments:
            - 'Cerad\Bundle\AccountBundle\Entity\AccountIdentifier'
