services:
  
    cerad_account.entity_manager:
        alias: doctrine.orm.accounts_entity_manager # Need to tie this to cerad_account.model_manager_name
    
    # ===========================================================
    # Use fos naming schemes for now
    cerad_account.user_provider:
        class: Cerad\Bundle\AccountBundle\Security\UserProvider
        arguments: 
            - '@fos_user.user_manager'
        #   - '@cerad_person.manager'
        
    cerad_account.user_encoder:
        class: Cerad\Bundle\AccountBundle\Security\UserEncoder
        arguments: [%cerad_account.master_password%]
        
    cerad_account.user_manager:
        class: Cerad\Bundle\AccountBundle\Security\UserManager
        arguments:
            - '@security.encoder_factory'
            - '@fos_user.util.canonicalizer.default'
            - '@fos_user.util.canonicalizer.default'
            - '@cerad_account.entity_manager'
            - '%cerad_account.user_class%'
            - '%cerad_account.user_identifier_class%'
            
    cerad_account.account_manager:
        alias: cerad_account.user_manager
        
    cerad_account.account.manager:
        alias: cerad_account.user_manager
            
    cerad_account.user_checker:
        class: Symfony\Component\Security\Core\User\UserChecker
        
    cerad_account.login_manager:
        class: Cerad\Bundle\AccountBundle\Security\LoginManager
        arguments:
            - '@security.context'
            - '@cerad_account.user_checker'
       
    cerad_account.authentication_information:
        class: Cerad\Bundle\AccountBundle\Security\AuthenticationInformation
      
    # ==========================================================
    # My listeners
    cerad_account.registration_listener:
        class: Cerad\Bundle\AccountBundle\EventListener\RegistrationListener
        tags:
            - { name: kernel.event_subscriber }
    
    # REGISTRATION_COMPLETED, REGISTRATION_CONFIRMED, RESETTING_RESET_COMPLETED
    cerad_account.authentication_listener:
        class: FOS\UserBundle\EventListener\AuthenticationListener
        arguments:
            - '@cerad_account.login_manager'
            - '%cerad_account.firewall_name%'            
        tags:
            - { name: kernel.event_subscriber }          
    
    # ==============================================================
    # Lost of form types
            
    cerad_account.create.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\CreateFormType
        tags:
            - { name: form.type, alias: cerad_account_create }
            
    cerad_account.edit.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\EditFormType
        tags:
            - { name: form.type, alias: cerad_account_edit }
    
    cerad_account.displayname.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\DisplayNameFormType
        tags:
            - { name: form.type, alias: cerad_account_displayname }
            
    cerad_account.username.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\UsernameFormType
        tags:
            - { name: form.type, alias: cerad_account_username }
            
    cerad_account.username.unique.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\UsernameUniqueFormType
        tags:
            - { name: form.type, alias: cerad_account_username_unique }
            
    cerad_account.username.existing.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\UsernameExistingFormType
        tags:
            - { name: form.type, alias: cerad_account_username_existing }
            
    cerad_account.email.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\EmailFormType
        tags:
            - { name: form.type, alias: cerad_account_email }
            
    cerad_account.email.unique.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\EmailUniqueFormType
        tags:
            - { name: form.type, alias: cerad_account_email_unique }
            
    cerad_account.password.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\PasswordFormType
        tags:
            - { name: form.type, alias: cerad_account_password }
            
    cerad_account.password_reset.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\PasswordResetFormType
        tags:
            - { name: form.type, alias: cerad_account_password_reset }
            
    cerad_account.signin.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\SigninFormType
        tags:
            - { name: form.type, alias: cerad_account_signin }
            
    cerad_account.token.form_type:
        class: Cerad\Bundle\AccountBundle\Form\Type\TokenFormType
        tags:
            - { name: form.type, alias: cerad_account_token }

    # ===================================================
    # Some FOS Services, keep the name for now
    fos_user.user_manager:
        alias: cerad_account.user_manager
    
    fos_user.util.canonicalizer.default:
        class: FOS\UserBundle\Util\Canonicalizer
      
    fos_user.util.user_manipulator:
        class: FOS\UserBundle\Util\UserManipulator
        arguments:
            - '@fos_user.user_manager'

    fos_user.util.token_generator:
        class: FOS\UserBundle\Util\TokenGenerator
        arguments:
            - '@logger'
