cerad_tourn_index:
  path: /
  defaults:  { _controller: CeradTournBundle:Main:index }
  
cerad_tourn_welcome:
  path: /welcome
  defaults:  { _controller: CeradTournBundle:Main:welcome }
  
cerad_tourn_home:
  path: /home
  defaults:  { _controller: CeradTournBundle:Home:home }
  
cerad_tourn_textalerts:
  path: /textalerts
  defaults:  { _controller: CeradTournBundle:Main:welcome }
  
cerad_tourn_contact:
  path: /contact
  defaults:  { _controller: CeradTournBundle:Main:contact }
  
cerad_tourn_schedule:
  path: /schedule
  defaults:  { _controller: CeradTournBundle:Main:welcome }
  
cerad_tourn_schedule_team_list:
  path: /schedule/team
  defaults:  { _controller: CeradTournBundle:Main:welcome }
  
cerad_tourn_schedule_my_list:
  path: /schedule/my
  defaults:  { _controller: CeradTournBundle:Schedule:my }
  
cerad_tourn_schedule_referee_list:
  path: /schedule/referee.{_format}
  defaults:  { _controller: CeradTournBundle:Referee:referee, _format: html }
  requirements:
    _format:  html|csv|xls|pdf
  
cerad_tourn_schedule_referee_assign:
  path: /schedule/referee/assign/{id}
  defaults:  { _controller: CeradTournBundle:Referee:assign, id: 0 }
  requirements:
    id: \d+
    
cerad_tourn_game_report:
  path: /game/report/{num}
  defaults:  { _controller: CeradTournBundle:GameReport:report }

# ===================================================
# Results
cerad_tourn_results_poolplay:
  path: /results/poolplay/{div}/{poolFilter}
  defaults:  { _controller: CeradTournBundle:Results:poolplay, div: null, poolFilter: null }
  
cerad_tourn_results_playoffs:
  path: /results/playoffs
  defaults:  { _controller: CeradTournBundle:Results:playoffs }
  
cerad_tourn_results_champions:
  path: /results/champions
  defaults:  { _controller: CeradTournBundle:Results:champions }
  
cerad_tourn_results_sportsmanship:
  path: /results/sportsmanship
  defaults:  { _controller: CeradTournBundle:Results:sportsmanship }

# ==============================================================
# Person stuff
# Need to add personId at some point

cerad_tourn_person_plan:
  path: /person/plan/{id}
  defaults:  { _controller: CeradTournBundle:Person:plan, id: null }
  
cerad_tourn_person_plan_success:
  path: /person/plan-success{id}
  defaults:  { _controller: CeradTournBundle:Person:plan, id: null }
  
cerad_tourn_person_plan_failure:
  path: /person/plan-failure/{id}
  defaults:  { _controller: CeradTournBundle:Person:plan, id: null }
  
cerad_tourn_person_plan_form:
  path: /person/plan-form/{id}
  defaults:  { _controller: CeradTournBundle:Person:planForm, id: null }
  
cerad_tourn_person_person_add:
  path: /person/person/add
  defaults:  { _controller: CeradTournBundle:PersonPerson:add }
 
# ==============================================================
# Not entirely sure about this
cerad_tourn_account_signin:
  path: /account/signin
  defaults:  { _controller: CeradTournBundle:Account:signin }
  
cerad_tourn_account_signin_form:
  path: /account/signin-form
  defaults:  { _controller: CeradTournBundle:Account:signinForm }
  
#cerad_tourn_account_create:
#  path: /account/create
#  defaults:  { _controller: CeradTournBundle:Account:create }
  
cerad_tourn_account_create_success:
  path: /account/create-success
  defaults:  { _controller: CeradTournBundle:Account:create }
  
cerad_tourn_account_create_failure:
  path: /account/create-failure
  defaults:  { _controller: CeradTournBundle:Account:create }
  
cerad_tourn_account_create_form:
  path: /account/create-form
  defaults:  { _controller: CeradTournBundle:Account:createForm }
  
cerad_tourn_account_edit:
    pattern:  /account/edit/{id}
    defaults: { _controller: CeradTournBundle:Account:create, id: 0 }
    requirements:
        id: \d+
        
cerad_tourn_account_person_edit:
    pattern:  /account/person/edit/{id}
    defaults: { _controller: CeradTournBundle:Account/Person:edit, id: 0 }
    requirements:
        id: \d+
        
cerad_tourn_person_person_edit:
    pattern:  /person-person/edit/{id}
    defaults: { _controller: CeradTournBundle:Main:welcome, id: 0 }
    requirements:
        id: \d+
        
# ==============================================================
# Some testing stuff
cerad_tourn_test_form1:
  path: /test/form1
  defaults:  { _controller: CeradTournBundle:Test:form1 }
  
cerad_tourn_test_form1_success:
  path: /test/form1-success
  defaults:  { _controller: CeradTournBundle:Test:form1 }
  
cerad_tourn_test_form1_failure:
  path: /test/form1-failure
  defaults:  { _controller: CeradTournBundle:Test:form1 }
  
cerad_tourn_test_simple:
  path: /test/simple
  defaults:  { _controller: CeradTournBundle:Test:simple }

