services:
  
    cerad_tourn.schedule.manager:
        class:  Cerad\Bundle\TournBundle\Schedule\ScheduleManager
        arguments:  
            - '@cerad.project.repository'
            - '@cerad.level.repository'
            - '@cerad.field.repository'
            - '@cerad.game.repository'
            - '@cerad_person.repository'
            
    cerad_tourn.results.manager:
        class:  Cerad\Bundle\TournBundle\Schedule\ResultsManager
        arguments:  
            - '@cerad.game.repository'
      
    cerad_tourn.schedule.import:
        class:  Cerad\Bundle\TournBundle\Schedule\ScheduleImport
        arguments:  
            - '@cerad_tourn.schedule.manager'
            
    cerad_tourn.schedule.referee.search.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Schedule\Referee\SearchFormType
        arguments:  
            - '@cerad_tourn.schedule.manager'
            - '@cerad_tourn.project'
        tags:
            - { name: form.type, alias: schedule_referee_search }
            
    cerad_tourn.schedule.referee.assign.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Schedule\Referee\AssignFormType
        arguments:  
            - '@cerad_tourn.schedule.manager'
        tags:
            - { name: form.type, alias: schedule_referee_assign }

    cerad_tourn.account.create.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Account\CreateFormType
        arguments:  
            - '@cerad_tourn.schedule.manager'
        tags:
            - { name: form.type, alias: cerad_tourn_account_create }
            
    cerad_tourn.person_plan.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Person\PlanFormType
        tags:
            - { name: form.type, alias: cerad_tourn_person_plan }
            
    cerad_tourn.account.person.edit.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Person\EditFormType
        tags:
            - { name: form.type, alias: cerad_tourn_person_edit }

    cerad_tourn.person.person.add.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Person\Person\AddFormType
        tags:
            - { name: form.type, alias: cerad_tourn_person_person_add }

    cerad_tourn.test.form1.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Test\Form1FormType
        tags:
            - { name: form.type, alias: cerad_tourn_test_form1 }

    cerad_tourn.project:
        class:  Cerad\Bundle\TournBundle\Model\Project
        arguments:  
            - '%cerad_tourn_project%'
            
    cerad_tourn.twig.extension:
        class:  Cerad\Bundle\TournBundle\Twig\TournExtension
        arguments:  
            - '@cerad_tourn.project'
            - '%cerad_tourn_show_configs%'
        tags:
            - { name: twig.extension }
            
    cerad_tourn.excel:
        class:  Cerad\Component\Excel\Excel
        
    cerad_tourn.schedule.referee.export.csv:
        class:  Cerad\Bundle\TournBundle\Schedule\Referee\ScheduleExportCSV
            
    cerad_tourn.schedule.referee.export.xls:
        class:  Cerad\Bundle\TournBundle\Schedule\Referee\ScheduleExportXLS
        arguments:  
            - '@cerad_tourn.excel'


     