services:
  
    cerad_tourn.schedule.manager:
        class:  Cerad\Bundle\TournBundle\Schedule\ScheduleManager
        arguments:  
            - '@cerad.project.repository'
            - '@cerad.level.repository'
            - '@cerad.field.repository'
            - '@cerad.game.repository'
            - '@cerad_person.repository'
      
    cerad_tourn.schedule.import:
        class:  Cerad\Bundle\TournBundle\Schedule\ScheduleImport
        arguments:  
            - '@cerad_tourn.schedule.manager'
            
    cerad_tourn.schedule.referee.search.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Schedule\Referee\SearchFormType
        arguments:  
            - '@cerad_tourn.schedule.manager'
        tags:
            - { name: form.type, alias: schedule_referee_search }
            
    cerad_tourn.schedule.referee.assign.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Schedule\Referee\AssignFormType
        arguments:  
            - '@cerad_tourn.schedule.manager'
        tags:
            - { name: form.type, alias: schedule_referee_assign }

    cerad_tourn.account.create.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Account\CreateFormType
        arguments:  
            - '@cerad_tourn.schedule.manager'
        tags:
            - { name: form.type, alias: cerad_tourn_account_create }
            
    cerad_tourn.person_plan.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Person\PlanFormType
        tags:
            - { name: form.type, alias: cerad_tourn_person_plan }

    cerad_tourn.test.form1.formtype:
        class:  Cerad\Bundle\TournBundle\Form\Type\Test\Form1FormType
        tags:
            - { name: form.type, alias: cerad_tourn_test_form1 }

    cerad_tourn.project:
        class:  Cerad\Bundle\TournBundle\Model\Project
        arguments:  
            - '%cerad_tourn_project%'
     