Cerad\Bundle\PersonBundle\Entity\PersonIdentifier:
  
    type:  entity
    table: person_identifier
                
    manyToOne:
        entity:
            targetEntity: Person
            inversedBy:   identifiers
    