Cerad\Bundle\PersonBundle\Entity\PersonCert:
    type:  entity
    table: person_cert
    changeTrackingPolicy: NOTIFY
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    manyToOne:
      
        person:
            targetEntity: Person
            inversedBy:   certs
             
    fields:
        fed:
            column:   fed
            type:     string
            length:   20
            nullable: false
            
        role:
            column:   role
            type:     string
            length:   20
            nullable: false
            
        identifier:
            column:   identifier
            type:     string
            length:   80
            nullable: false
             
        badge:
            type:     string
            length:   20
            nullable: true
            
        badgex:
            type:     string
            length:   20
            nullable: true
            
        dateFirstCertified:
            column:   date_cert
            type:     date
            nullable: true
            
        dateLastUpgraded:
            column:   date_upgraded
            type:     date
            nullable: true
           
        upgrading:
            type:     string
            length:   20
            nullable: true
          
        verified:
            type:     string
            length:   20
            nullable: true
            
        status:
            type:     string
            length:   20
            nullable: false
