Cerad\Bundle\PersonBundle\Entity\PersonLeague:
    type:  entity
    table: person_league
    changeTrackingPolicy: NOTIFY
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    manyToOne:
      
        person:
            targetEntity: Person
            inversedBy:   leagues
             
    fields:
        fed:
            column:   fed
            type:     string
            length:   20
            nullable: false
            
        role:
            column:   role
            type:     string
            length:   20
            nullable: false
            
        league:
            column:   league
            type:     string
            length:   40
            nullable: true
            
        identifier:
            column:   identifier
            type:     string
            length:   40
            nullable: false
            
        cvpa:
            column:   cvpa
            type:     string
            length:   20
            nullable: true
            
        memId:
            column:   mem_id
            type:     string
            length:   40
            nullable: true

        memYear:
            column:   mem_year
            type:     string
            length:   20
            nullable: true
            
        memFirstRegistered:
            column:   mem_first
            type:     date
            nullable: true
            
        memLastRegistered:
            column:   mem_last
            type:     date
            nullable: true
            
        memExpires:
            column:   mem_expires
            type:     date
            nullable: true
            
        backgroundCheckFirst:
            column:   bc_first
            type:     date
            nullable: true
            
        backgroundCheckLast:
            column:   bc_last
            type:     date
            nullable: true
            
        backgroundCheckExpires:
            column:   bc_expires
            type:     date
            nullable: true
           
        verified:
            type:     string
            length:   20
            nullable: true
            
        status:
            type:     string
            length:   20
            nullable: false
