Cerad\Bundle\Legacy2012Bundle\Entity\EventPerson:
    type:                 entity
    table:                event_person
    changeTrackingPolicy: NOTIFY
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    manyToOne:
        project:
            targetEntity: Project
            nullable:     false
        event:
            targetEntity: Event
            nullable:     false
            inversedBy:   teams
            
        person:
            targetEntity: Person
            nullable:     true
           
    fields: 
            
        type:
            column:   type
            type:     string
            length:   20
            nullable: false
            
        datax:
            type:     text
            nullable: true
