services:
  
    cerad_arbiter.schedule.manager:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\ScheduleManager
        arguments:  
            - '@cerad_gamev2.project.manager'
            - '@cerad_gamev2.level.manager'
            - '@cerad_gamev2.field.manager'
            - '@cerad.game.repository'

    cerad_arbiter.schedule.import.master:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Import\ImportScheduleMaster
        arguments:  
            - '@cerad_arbiter.schedule.manager'
           #- '@cerad_schedule.format.excel'
           
    cerad_arbiter.excel.reader:
        class:  Cerad\Component\Excel\Reader
        
    cerad_arbiter.schedule.tourn.les.load:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\LoadLesSchedule
        
    cerad_arbiter.schedule.tourn.arbiter.load:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\LoadArbiterSchedule

    cerad_arbiter.schedule.tourn.arbiter.save:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\SaveArbiterSchedule
        
    cerad_arbiter.schedule.tourn.referee.save:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\SaveRefereeSchedule
        
