services:
  
    cerad_arbiter.schedule.manager:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\ScheduleManager
        arguments:  
            - '@cerad.project.repository'
            - '@cerad.level.repository'
            - '@cerad.field.repository'
            - '@cerad.game.repository'

    cerad_arbiter.schedule.import.master:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Import\ImportScheduleMaster
        arguments:  
            - '@cerad_arbiter.schedule.manager'
           #- '@cerad_schedule.format.excel'
           
    cerad_arbiter.excel.reader:
        class:  Cerad\Component\Excel\Reader
        
    cerad_arbiter.schedule.tourn.les.load:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\LoadLesSchedule
#       arguments:  
#          - '@cerad_arbiter.excel.reader'
        
