# ==========================================
# Overrides for class names, 
# Eventually most of the classes will have these parameters
parameters:
      cerad_person.ayso_referee_badge.form_type.class:
          Cerad\Bundle\PersonBundle\Form\Type\AYSO\RefereeBadgeFormType

# ===========================================
# And the services
services:
  
    cerad_person.entity_manager:
        alias: doctrine.orm.persons_entity_manager
        
    cerad_person.repository:
        class:  Cerad\Bundle\PersonBundle\EntityRepository\PersonRepository
        factory_service: 'cerad_person.entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\PersonBundle\Entity\Person'

    cerad_person.manager:
        alias: cerad_person.repository
        
# =======================================================
# Data transformers
    cerad_person.ayso_region_id.datatransformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\AYSO\RegionIDTransformer
    
    cerad_person.ayso_region_entity.datatransformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\AYSO\RegionEntityTransformer
        arguments:  
            - '@cerad_person.manager' # Should be league manager
            
    cerad_person.ayso_volunteer_id.datatransformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\AYSO\VolunteerIDTransformer
        
    cerad_person.phone.datatransformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\PhoneTransformer
 
# =======================================================
# Form types
    cerad_person.person.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\PersonFormType
        tags:
            - { name: form.type, alias: cerad_person }
        arguments:  
            - '@cerad_person.manager'
          
    cerad_person.person.form_type.admin:
        class: Cerad\Bundle\PersonBundle\Form\Type\PersonFormType
        tags:
            - { name: form.type, alias: cerad_person_admin }
        arguments:  
            - '@cerad_person.manager'
            - 'admin'
            
    cerad_person.phone.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\PhoneFormType
        tags:
            - { name: form.type, alias: cerad_person_phone }
            
    cerad_person.email.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\EmailFormType
        tags:
            - { name: form.type, alias: cerad_person_email }
            
    cerad_person.ayso_region_id.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\AYSO\RegionIDFormType
        tags:
            - { name: form.type, alias: cerad_person_ayso_region_id }
            
    cerad_person.ayso_volunteer_id.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\AYSO\VolunteerIDFormType
        tags:
            - { name: form.type, alias: cerad_person_ayso_volunteer_id }
            
    cerad_person.ayso_referee_badge.form_type:
        class: '%cerad_person.ayso_referee_badge.form_type.class%'
        tags:
            - { name: form.type, alias: cerad_person_ayso_referee_badge }

    cerad_person.ayso_volunteer_region.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\AYSO\VolunteerRegionFormType
        tags:
            - { name: form.type, alias: cerad_person_ayso_volunteer_region }

# ===============================
    cerad_person.ayso_referee_create.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\AYSO\RefereeCreateFormType
        tags:
            - { name: form.type, alias: cerad_person_ayso_referee_create }
            
    cerad_person.ayso_volunteer.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\AYSO\VolunteerFormType
        tags:
            - { name: form.type, alias: cerad_person_ayso_volunteer }
            
    cerad_person.ayso_referee_cert.form_type:
        class: Cerad\Bundle\PersonBundle\Form\Type\AYSO\RefereeCertFormType
        tags:
            - { name: form.type, alias: cerad_person_ayso_referee_cert }
            
    cerad_person.twig_extension:
        class:  Cerad\Bundle\PersonBundle\Twig\PersonTwigExtension
        arguments:  
          - '@cerad_person.phone.datatransformer'
        tags:
          - { name: twig.extension }
          
# Funky event listeners
    cerad_person.event_listener:
        class:  Cerad\Bundle\PersonBundle\EventListener\PersonEventListener
        tags:   
          - { name: kernel.event_subscriber }
        arguments:
          - '@cerad_person.repository'
