Cerad\Bundle\CommonBundle\Entity\BaseEntityPrimary:
  
    type:  mappedSuperclass

    changeTrackingPolicy: NOTIFY
          
    id:
       id:
           type:   string
           length: 40
           generator: { strategy: NONE }
    
    fields:
            
        name:
            column:   name
            type:     string
            length:   80
            nullable: false
