Cerad\Bundle\AccountBundle\Entity\AccountUser:
    type:  entity
    table: account_user
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    fields:
    
        name:
            column:   name
            type:     string
           #length:   40
            nullable: true
            
        person:
            column:   person_uid
            type:     string
            length:   32
            nullable: true

