Cerad\Bundle\GameV2Bundle\Entity\BaseEntityProjectRelation:
  
    type:  mappedSuperclass

    changeTrackingPolicy: NOTIFY
    
    manyToOne:
        project:
            targetEntity: Project
            nullable:     false
           
    id:
       id:
           type:   integer
           generator: { strategy: AUTO }
                
    fields:
        name:
            type:     string
            length:   60
            nullable: true
            
        sort:
            column:   sortx
            type:     integer
            nullable: true
            
        status:
            type:     string
            length:   20
            nullable: true
           
