Cerad\Bundle\GameV2Bundle\Entity\FieldField:
  
    type:  entity
    table: field_field
                
    manyToOne:
        entity1:
            targetEntity: Field
            
        entity2:
            targetEntity: Field

    
