Cerad\Bundle\GameV2Bundle\Entity\Field:
  
    type:  entity
    table: field
    
    repositoryClass: Cerad\Bundle\GameV2Bundle\EntityRepository\FieldRepository
    
    changeTrackingPolicy: NOTIFY
                    
    oneToMany:
      
      identifiers:
          targetEntity: FieldIdentifier
          mappedBy:     entity
          cascade:      ['all']
          
      fieldProjects:
        targetEntity: ProjectField
        mappedBy:     entity2  # Slave to master
        cascade:      ['all']
        
      fieldFields1:
        targetEntity: FieldField
        mappedBy:     entity2  # Slave to master
        cascade:      ['all']
        
      fieldFields2:
        targetEntity: FieldField
        mappedBy:     entity1  # Master to slave
        cascade:      ['all']
                
    fields:
            
        venue:
            column:   venue
            type:     string
            length:   40
            nullable: true
                    
        checkConflicts:
            column: check_conflicts
            type:   boolean
            
        url:
            column:   url
            type:     string
            nullable: true
            
        latitude:
            column:   latitude
            type:     string
            length:   32
            nullable: true
            
        longitude:
            column:   longitude
            type:     string
            length:   32
            nullable: true

        status:
            column:   status
            type:     string
            length:   20
            nullable: true
