Cerad\Bundle\GameV2Bundle\Entity\Level:
  
    type:  entity
    table: level
    
    repositoryClass: Cerad\Bundle\GameV2Bundle\EntityRepository\LevelRepository
    
    changeTrackingPolicy: NOTIFY

    oneToMany:
      identifiers:
          targetEntity: LevelIdentifier
          mappedBy:     entity
          cascade:      ['all']
          
      levelProjects:
        targetEntity: ProjectLevel
        mappedBy:     entity2  # Slave to master
        cascade:      ['all']
        
      levelLevels1:
        targetEntity: LevelLevel
        mappedBy:     entity2  # Slave to master
        cascade:      ['all']
        
      levelLevels2:
        targetEntity: LevelLevel
        mappedBy:     entity1  # Master to slave
        cascade:      ['all']
     
    fields:
            
        age:
            column:   age
            type:     string
            length:   20
            nullable: true
            
        gender:
            column:   gender
            type:     string
            length:   20
            nullable: true
            
        program:
            column:   program
            type:     string
            length:   20
            nullable: true
            
        division:
            column:   division
            type:     string
            length:   20
            nullable: true
            
        status:
            column:   status
            type:     string
            length:   20
            nullable: true
