Cerad\Bundle\GameV2Bundle\Entity\ProjectLevel:
  
    type:  entity
    table: project_level
                
    manyToOne:
        entity1:
            targetEntity: Project
            
        entity2:
            targetEntity: Level

    
