Cerad\Bundle\GameV2Bundle\Entity\Project:
  
    type:  entity
    table: project
    
    repositoryClass: Cerad\Bundle\GameV2Bundle\EntityRepository\ProjectRepository
    
    changeTrackingPolicy: NOTIFY
    
    oneToMany:
            
      identifiers:
        targetEntity: ProjectIdentifier
        mappedBy:     entity
        cascade:      ['all']
        
      projectTeams:
        targetEntity: ProjectTeam
        mappedBy:     entity1
        cascade:      ['all']
        
      projectFields:
        targetEntity: ProjectField
        mappedBy:     entity1
        cascade:      ['all']
        
      projectLevels:
        targetEntity: ProjectLevel
        mappedBy:     entity1
        cascade:      ['all']
       
    fields:
            
        desc:
            column:   descx
            type:     string
            length:   80
            nullable: true
            
        status:
            column:   status
            type:     string
            length:   20
            nullable: true
            
        sport:
            type:     string
            length:   20
            nullable: false
            
        source:
            type:     string
            length:   20
            nullable: false
            
        season:
            type:     string
            length:   20
            nullable: false
            
        domain:
            type:     string
            length:   20
            nullable: false
            
        domainSub:
            type:     string
            length:   40
            nullable: false
                      
        data:
            column:   datax
            type:     json_array
            nullable: true
