Cerad\Bundle\GameV2Bundle\Entity\ProjectIdentifier:
  
    type:  entity
    table: project_identifier
            
    manyToOne:
        entity:
            targetEntity: Project
            nullable:     false
    
