Cerad\Bundle\GameV2Bundle\Entity\ProjectField:
  
    type:  entity
    table: project_field
                
    manyToOne:
        entity1:
            targetEntity: Project
            
        entity2:
            targetEntity: Field

    
