Cerad\Bundle\GameV2Bundle\Entity\Team:
  
    type:  entity
    table: team
    
    repositoryClass: Cerad\Bundle\GameV2Bundle\EntityRepository\TeamRepository
    
    changeTrackingPolicy: NOTIFY
            
    oneToMany:
      
      identifiers:
          targetEntity: TeamIdentifier
          mappedBy:     entity
          cascade:      ['all']
          
      teamProjects:
        targetEntity: ProjectTeam
        mappedBy:     entity2  # Slave to master
        cascade:      ['all']
        
      teamTeams1:
        targetEntity: TeamTeam
        mappedBy:     entity2  # Slave to master
        cascade:      ['all']
        
      teamTeams2:
        targetEntity: TeamTeam
        mappedBy:     entity1  # Master to slave
        cascade:      ['all']
                  
    fields:
      
        role:
            column:   role
            type:     string
            length:   20
            nullable: true
            
        name:
            column:   name
            type:     string
            length:   80
            nullable: false
                        
        status:
            column:   status
            type:     string
            length:   20
            nullable: true
