Cerad\Bundle\GameV2Bundle\Entity\TeamTeam:
  
    type:  entity
    table: team_team
                
    manyToOne:
        entity1:
            targetEntity: Team
            
        entity2:
            targetEntity: Team

    
